version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
    - PGPASSWORD=password
  redis: 
    image: 'redis:latest'
  api:
    image: ericstevens1989/complex-api
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=password
      - PGPORT=5432
  client:
    stdin_open: true
    image: ericstevens1989/complex_client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
  worker:
    image: ericstevens1989/complex-worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    restart: always
    image: ericstevens1989/complex-nginx
    ports:
      - '3050:80'
    depends_on:
      - api
      - client

  
  


